# Annex: Key and sensitive variables {#sec-11vars}

The following table is a non-exhaustive list of some of the common key and sensitive variables found in operational microdata collected by UNHCR and partners, and some example actions that could be performed as needed.

Please note that the following variables may be considered key variables in one dataset and not another depending on the context, and the actions may or may not be relevant depending on the dataset and the context.

| Variable                                               | Example actions                                                                                                                                                                                                                                                                                                                                                        |
|-----------------|-------------------------------------------------------|
| Unique ID                                              | Replace with pseudonym (see section [Unique ID](anonymize.qmd#sec-5id))                                                                                                                                                                                                                                                                                                                            |
| Sample weight                                          | In the case of stratified sampling, the weight will have the same value for all records in the same strata. If the variable used to define the strata is a key variable, local suppression of that key variable should be avoided.                                                                                                                                     |
|                                                        | If local suppressions are done on the strata variable, then the record will have to be removed as the response to the strata variable is obvious from the weight variable.                                                                                                                                                                                             |
| Household size                                         | Convert to factor and treated as a categorical key variable.                                                                                                                                                                                                                                                                                                           |
|                                                        | Top code larger households, e.g.: 8+                                                                                                                                                                                                                                                                                                                                   |
|                                                        | Recode into groups useful to analysis, e.g.: 1, 2, 3-4, 5-6, 7-8, \>8                                                                                                                                                                                                                                                                                                  |
|                                                        | In the case of a hierarchical dataset, household size may be able to be recalculated by counting the number of individuals for each household in the individual dataset linked to the household dataset. In such a case, household size cannot be recoded without modifying the individual responses.                                                                  |
| Breakdown of household members by age, sex, etc.       | Only preserve level of detail useful to analysis.                                                                                                                                                                                                                                                                                                                      |
|                                                        | For household-level files, replace with ratio, e.g. proportion women, proportion men, proportion under 18, etc.                                                                                                                                                                                                                                                        |
| Location variables                                     | Administrative divisions -- In cases where some divisions have few observations, they can be regrouped into an 'other' category, for example. In cases where there are multiple administrative divisions in the dataset (e.g., admin 1, admin 2 and admin 3), the lower level (e.g., admin 3) could be removed if not used in the primary analysis and/or for weights. |
|                                                        | Populated place -- In cases where some places have few observations, they can be recoded into an 'other' category. In cases where the populated place is too detailed and not used in primary analysis and/or weights and there is another location variable (such as administrative division), it may be decided to remove this variable all together.                |
| Marital status                                         | Recode to 'married', 'widower', 'separated/divorced', and 'single' households. If polygamous households are common, the level 'married' should be divided accordingly.                                                                                                                                                                                                 |
| Age                                                    | Convert to factor and treated as a categorical key variable.                                                                                                                                                                                                                                                                                                           |
|                                                        | Recode into groups useful to analysis, e.g., \<18, 18-59 and \>59 or five- or ten-year intervals.                                                                                                                                                                                                                                                                      |
|                                                        | In the case of SENS surveys children's module, age in months should be rounded to the nearest month but not grouped as that would be removed the value of the variable (see section 11.6.2.2).                                                                                                                                                                         |
| Gender                                                 | In most cases this variable contains only two categories (male/female). In case other categories are present (e.g.: transgender etc.) they may be recoded under the category 'other' if appropriate.                                                                                                                                                                   |
| Country of origin, country of birth, nationality, etc. | In cases where some categories have few observations, they can be regrouped into a different category or an 'other' category.                                                                                                                                                                                                                                          |
| Variables related to sexual and gender-based violence. | This should be discussed with the Data Provider.                                                                                                                                                                                                                                                                                                                       |
| Language                                               | In cases where some categories have few observations, they can be regrouped into a different category or an 'other' category.                                                                                                                                                                                                                                          |
| Income                                                 | Round to avoid exact matching.                                                                                                                                                                                                                                                                                                                                         |
|                                                        | Top code outliers.                                                                                                                                                                                                                                                                                                                                                     |
|                                                        | Recode into groups useful for analysis.                                                                                                                                                                                                                                                                                                                                |
| Open text variables                                    | See section [Free text variables](anonymize.qmd#sec-5freetext).                                                                                                                                                                                                                                                                                                                               |
